server:
  servlet:
    context-path: /produdoro/api

spring:
  data:
    mongodb:
      authentication-database: admin
      uri: mongodb+srv://marcio:46ZShXy4WfOvv2Hl@wakanda.7vjde1f.mongodb.net/wakanda?retryWrites=true&w=majority
      auto-index-creation: true

springdoc:
  swagger-ui:
    path: /swagger
      

